export const FETCH = 'FETCH';
export const FETCH_IF_NEEDED = 'FETCH_IF_NEEDED';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const DELETE = 'DELETE';
export const DELETE_PENDING = 'DELETE_PENDING';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';

export const CREATE = 'CREATE';
export const CREATE_PENDING = 'CREATE_PENDING';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_FAILURE';

export const UPDATE = 'UPDATE';
export const UPDATE_PENDING = 'UPDATE_PENDING';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';
